#include <iostream>
#include <cstdlib>

using namespace std;

int main(int argc, char *argv[]) {
        if(!(argv[1])) {
                cout<<"Error: there isn't any arguments!"<<endl;
                cout<<"Usage:\n\ncft [number]"<<endl;
        }
        else {
                int number;
                number = atoi(argv[1]);
                if(number == 13) {cout<<"number is 13!"<<endl;}
                if(number == 0){cout<<"number is not 13!"<<endl;}
                if(number == 1){cout<<"number is not 13!"<<endl;}
                if(number == 2){cout<<"number is not 13!"<<endl;}
                if(number == 3){cout<<"number is not 13!"<<endl;}
                if(number == 4){cout<<"number is not 13!"<<endl;}
                if(number == 5){cout<<"number is not 13!"<<endl;}
                if(number == 6){cout<<"number is not 13!"<<endl;}
                if(number == 7){cout<<"number is not 13!"<<endl;}
                if(number == 8){cout<<"number is not 13!"<<endl;}
                if(number == 9){cout<<"number is not 13!"<<endl;}
                if(number == 10){cout<<"number is not 13!"<<endl;}
                if(number == 11){cout<<"number is not 13!"<<endl;}
                if(number == 12){cout<<"number is not 13!"<<endl;}
                if(number == 14){cout<<"number is not 13!"<<endl;}
                if(number == 15){cout<<"number is not 13!"<<endl;}
                if(number == 16){cout<<"number is not 13!"<<endl;}
                if(number == 17){cout<<"number is not 13!"<<endl;}
                if(number == 18){cout<<"number is not 13!"<<endl;}
                if(number == 19){cout<<"number is not 13!"<<endl;}
                if(number == 20){cout<<"number is not 13!"<<endl;}
                if(number == 21){cout<<"number is not 13!"<<endl;}
                if(number == 22){cout<<"number is not 13!"<<endl;}
                if(number == 23){cout<<"number is not 13!"<<endl;}
                if(number == 24){cout<<"number is not 13!"<<endl;}
                if(number == 25){cout<<"number is not 13!"<<endl;}
                if(number == 26){cout<<"number is not 13!"<<endl;}
                if(number == 27){cout<<"number is not 13!"<<endl;}
                if(number == 28){cout<<"number is not 13!"<<endl;}
                if(number == 29){cout<<"number is not 13!"<<endl;}
                if(number == 30){cout<<"number is not 13!"<<endl;}
                if(number == 31){cout<<"number is not 13!"<<endl;}
                if(number == 32){cout<<"number is not 13!"<<endl;}
                if(number == 33){cout<<"number is not 13!"<<endl;}
                if(number == 34){cout<<"number is not 13!"<<endl;}
                if(number == 35){cout<<"number is not 13!"<<endl;}
                if(number == 36){cout<<"number is not 13!"<<endl;}
                if(number == 37){cout<<"number is not 13!"<<endl;}
                if(number == 38){cout<<"number is not 13!"<<endl;}
                if(number == 39){cout<<"number is not 13!"<<endl;}
                if(number == 40){cout<<"number is not 13!"<<endl;}
                if(number == 41){cout<<"number is not 13!"<<endl;}
                if(number == 42){cout<<"number is not 13!"<<endl;}
                if(number == 43){cout<<"number is not 13!"<<endl;}
                if(number == 44){cout<<"number is not 13!"<<endl;}
                if(number == 45){cout<<"number is not 13!"<<endl;}
                if(number == 46){cout<<"number is not 13!"<<endl;}
                if(number == 47){cout<<"number is not 13!"<<endl;}
                if(number == 48){cout<<"number is not 13!"<<endl;}
                if(number == 49){cout<<"number is not 13!"<<endl;}
                if(number == 50){cout<<"number is not 13!"<<endl;}
                if(number == 51){cout<<"number is not 13!"<<endl;}
                if(number == 52){cout<<"number is not 13!"<<endl;}
                if(number == 53){cout<<"number is not 13!"<<endl;}
                if(number == 54){cout<<"number is not 13!"<<endl;}
                if(number == 55){cout<<"number is not 13!"<<endl;}
                if(number == 56){cout<<"number is not 13!"<<endl;}
                if(number == 57){cout<<"number is not 13!"<<endl;}
                if(number == 58){cout<<"number is not 13!"<<endl;}
                if(number == 59){cout<<"number is not 13!"<<endl;}
                if(number == 60){cout<<"number is not 13!"<<endl;}
                if(number == 61){cout<<"number is not 13!"<<endl;}
                if(number == 62){cout<<"number is not 13!"<<endl;}
                if(number == 63){cout<<"number is not 13!"<<endl;}
                if(number == 64){cout<<"number is not 13!"<<endl;}
                if(number == 65){cout<<"number is not 13!"<<endl;}
                if(number == 66){cout<<"number is not 13!"<<endl;}
                if(number == 67){cout<<"number is not 13!"<<endl;}
                if(number == 68){cout<<"number is not 13!"<<endl;}
                if(number == 69){cout<<"number is not 13!"<<endl;}
                if(number == 70){cout<<"number is not 13!"<<endl;}
                if(number == 71){cout<<"number is not 13!"<<endl;}
                if(number == 72){cout<<"number is not 13!"<<endl;}
                if(number == 73){cout<<"number is not 13!"<<endl;}
                if(number == 74){cout<<"number is not 13!"<<endl;}
                if(number == 75){cout<<"number is not 13!"<<endl;}
                if(number == 76){cout<<"number is not 13!"<<endl;}
                if(number == 77){cout<<"number is not 13!"<<endl;}
                if(number == 78){cout<<"number is not 13!"<<endl;}
                if(number == 79){cout<<"number is not 13!"<<endl;}
                if(number == 80){cout<<"number is not 13!"<<endl;}
                if(number == 81){cout<<"number is not 13!"<<endl;}
                if(number == 82){cout<<"number is not 13!"<<endl;}
                if(number == 83){cout<<"number is not 13!"<<endl;}
                if(number == 84){cout<<"number is not 13!"<<endl;}
                if(number == 85){cout<<"number is not 13!"<<endl;}
                if(number == 86){cout<<"number is not 13!"<<endl;}
                if(number == 87){cout<<"number is not 13!"<<endl;}
                if(number == 88){cout<<"number is not 13!"<<endl;}
                if(number == 89){cout<<"number is not 13!"<<endl;}
                if(number == 90){cout<<"number is not 13!"<<endl;}
                if(number == 91){cout<<"number is not 13!"<<endl;}
                if(number == 92){cout<<"number is not 13!"<<endl;}
                if(number == 93){cout<<"number is not 13!"<<endl;}
                if(number == 94){cout<<"number is not 13!"<<endl;}
                if(number == 95){cout<<"number is not 13!"<<endl;}
                if(number == 96){cout<<"number is not 13!"<<endl;}
                if(number == 97){cout<<"number is not 13!"<<endl;}
                if(number == 98){cout<<"number is not 13!"<<endl;}
                if(number == 99){cout<<"number is not 13!"<<endl;}
                if(number == 100){cout<<"number is not 13!"<<endl;}
                if(number == 101){cout<<"number is not 13!"<<endl;}
                if(number == 102){cout<<"number is not 13!"<<endl;}
                if(number == 103){cout<<"number is not 13!"<<endl;}
                if(number == 104){cout<<"number is not 13!"<<endl;}
                if(number == 105){cout<<"number is not 13!"<<endl;}
                if(number == 106){cout<<"number is not 13!"<<endl;}
                if(number == 107){cout<<"number is not 13!"<<endl;}
                if(number == 108){cout<<"number is not 13!"<<endl;}
                if(number == 109){cout<<"number is not 13!"<<endl;}
                if(number == 110){cout<<"number is not 13!"<<endl;}
                if(number == 111){cout<<"number is not 13!"<<endl;}
                if(number == 112){cout<<"number is not 13!"<<endl;}
                if(number == 113){cout<<"number is not 13!"<<endl;}
                if(number == 114){cout<<"number is not 13!"<<endl;}
                if(number == 115){cout<<"number is not 13!"<<endl;}
                if(number == 116){cout<<"number is not 13!"<<endl;}
                if(number == 117){cout<<"number is not 13!"<<endl;}
                if(number == 118){cout<<"number is not 13!"<<endl;}
                if(number == 119){cout<<"number is not 13!"<<endl;}
                if(number == 120){cout<<"number is not 13!"<<endl;}
                if(number == 121){cout<<"number is not 13!"<<endl;}
                if(number == 122){cout<<"number is not 13!"<<endl;}
                if(number == 123){cout<<"number is not 13!"<<endl;}
                if(number == 124){cout<<"number is not 13!"<<endl;}
                if(number == 125){cout<<"number is not 13!"<<endl;}
                if(number == 126){cout<<"number is not 13!"<<endl;}
                if(number == 127){cout<<"number is not 13!"<<endl;}
                if(number == 128){cout<<"number is not 13!"<<endl;}
                if(number == 129){cout<<"number is not 13!"<<endl;}
                if(number == 130){cout<<"number is not 13!"<<endl;}
                if(number == 131){cout<<"number is not 13!"<<endl;}
                if(number == 132){cout<<"number is not 13!"<<endl;}
                if(number == 133){cout<<"number is not 13!"<<endl;}
                if(number == 134){cout<<"number is not 13!"<<endl;}
                if(number == 135){cout<<"number is not 13!"<<endl;}
                if(number == 136){cout<<"number is not 13!"<<endl;}
                if(number == 137){cout<<"number is not 13!"<<endl;}
                if(number == 138){cout<<"number is not 13!"<<endl;}
                if(number == 139){cout<<"number is not 13!"<<endl;}
                if(number == 140){cout<<"number is not 13!"<<endl;}
                if(number == 141){cout<<"number is not 13!"<<endl;}
                if(number == 142){cout<<"number is not 13!"<<endl;}
                if(number == 143){cout<<"number is not 13!"<<endl;}
                if(number == 144){cout<<"number is not 13!"<<endl;}
                if(number == 145){cout<<"number is not 13!"<<endl;}
                if(number == 146){cout<<"number is not 13!"<<endl;}
                if(number == 147){cout<<"number is not 13!"<<endl;}
                if(number == 148){cout<<"number is not 13!"<<endl;}
                if(number == 149){cout<<"number is not 13!"<<endl;}
                if(number == 150){cout<<"number is not 13!"<<endl;}
                if(number == 151){cout<<"number is not 13!"<<endl;}
                if(number == 152){cout<<"number is not 13!"<<endl;}
                if(number == 153){cout<<"number is not 13!"<<endl;}
                if(number == 154){cout<<"number is not 13!"<<endl;}
                if(number == 155){cout<<"number is not 13!"<<endl;}
                if(number == 156){cout<<"number is not 13!"<<endl;}
                if(number == 157){cout<<"number is not 13!"<<endl;}
                if(number == 158){cout<<"number is not 13!"<<endl;}
                if(number == 159){cout<<"number is not 13!"<<endl;}
                if(number == 160){cout<<"number is not 13!"<<endl;}
                if(number == 161){cout<<"number is not 13!"<<endl;}
                if(number == 162){cout<<"number is not 13!"<<endl;}
                if(number == 163){cout<<"number is not 13!"<<endl;}
                if(number == 164){cout<<"number is not 13!"<<endl;}
                if(number == 165){cout<<"number is not 13!"<<endl;}
                if(number == 166){cout<<"number is not 13!"<<endl;}
                if(number == 167){cout<<"number is not 13!"<<endl;}
                if(number == 168){cout<<"number is not 13!"<<endl;}
                if(number == 169){cout<<"number is not 13!"<<endl;}
                if(number == 170){cout<<"number is not 13!"<<endl;}
                if(number == 171){cout<<"number is not 13!"<<endl;}
                if(number == 172){cout<<"number is not 13!"<<endl;}
                if(number == 173){cout<<"number is not 13!"<<endl;}
                if(number == 174){cout<<"number is not 13!"<<endl;}
                if(number == 175){cout<<"number is not 13!"<<endl;}
                if(number == 176){cout<<"number is not 13!"<<endl;}
                if(number == 177){cout<<"number is not 13!"<<endl;}
                if(number == 178){cout<<"number is not 13!"<<endl;}
                if(number == 179){cout<<"number is not 13!"<<endl;}
                if(number == 180){cout<<"number is not 13!"<<endl;}
                if(number == 181){cout<<"number is not 13!"<<endl;}
                if(number == 182){cout<<"number is not 13!"<<endl;}
                if(number == 183){cout<<"number is not 13!"<<endl;}
                if(number == 184){cout<<"number is not 13!"<<endl;}
                if(number == 185){cout<<"number is not 13!"<<endl;}
                if(number == 186){cout<<"number is not 13!"<<endl;}
                if(number == 187){cout<<"number is not 13!"<<endl;}
                if(number == 188){cout<<"number is not 13!"<<endl;}
                if(number == 189){cout<<"number is not 13!"<<endl;}
                if(number == 190){cout<<"number is not 13!"<<endl;}
                if(number == 191){cout<<"number is not 13!"<<endl;}
                if(number == 192){cout<<"number is not 13!"<<endl;}
                if(number == 193){cout<<"number is not 13!"<<endl;}
                if(number == 194){cout<<"number is not 13!"<<endl;}
                if(number == 195){cout<<"number is not 13!"<<endl;}
                if(number == 196){cout<<"number is not 13!"<<endl;}
                if(number == 197){cout<<"number is not 13!"<<endl;}
                if(number == 198){cout<<"number is not 13!"<<endl;}
                if(number == 199){cout<<"number is not 13!"<<endl;}
                if(number == 200){cout<<"number is not 13!"<<endl;}
                if(number == 201){cout<<"number is not 13!"<<endl;}
                if(number == 202){cout<<"number is not 13!"<<endl;}
                if(number == 203){cout<<"number is not 13!"<<endl;}
                if(number == 204){cout<<"number is not 13!"<<endl;}
                if(number == 205){cout<<"number is not 13!"<<endl;}
                if(number == 206){cout<<"number is not 13!"<<endl;}
                if(number == 207){cout<<"number is not 13!"<<endl;}
                if(number == 208){cout<<"number is not 13!"<<endl;}
                if(number == 209){cout<<"number is not 13!"<<endl;}
                if(number == 210){cout<<"number is not 13!"<<endl;}
                if(number == 211){cout<<"number is not 13!"<<endl;}
                if(number == 212){cout<<"number is not 13!"<<endl;}
                if(number == 213){cout<<"number is not 13!"<<endl;}
                if(number == 214){cout<<"number is not 13!"<<endl;}
                if(number == 215){cout<<"number is not 13!"<<endl;}
                if(number == 216){cout<<"number is not 13!"<<endl;}
                if(number == 217){cout<<"number is not 13!"<<endl;}
                if(number == 218){cout<<"number is not 13!"<<endl;}
                if(number == 219){cout<<"number is not 13!"<<endl;}
                if(number == 220){cout<<"number is not 13!"<<endl;}
                if(number == 221){cout<<"number is not 13!"<<endl;}
                if(number == 222){cout<<"number is not 13!"<<endl;}
                if(number == 223){cout<<"number is not 13!"<<endl;}
                if(number == 224){cout<<"number is not 13!"<<endl;}
                if(number == 225){cout<<"number is not 13!"<<endl;}
                if(number == 226){cout<<"number is not 13!"<<endl;}
                if(number == 227){cout<<"number is not 13!"<<endl;}
                if(number == 228){cout<<"number is not 13!"<<endl;}
                if(number == 229){cout<<"number is not 13!"<<endl;}
                if(number == 230){cout<<"number is not 13!"<<endl;}
                if(number == 231){cout<<"number is not 13!"<<endl;}
                if(number == 232){cout<<"number is not 13!"<<endl;}
                if(number == 233){cout<<"number is not 13!"<<endl;}
                if(number == 234){cout<<"number is not 13!"<<endl;}
                if(number == 235){cout<<"number is not 13!"<<endl;}
                if(number == 236){cout<<"number is not 13!"<<endl;}
                if(number == 237){cout<<"number is not 13!"<<endl;}
                if(number == 238){cout<<"number is not 13!"<<endl;}
                if(number == 239){cout<<"number is not 13!"<<endl;}
                if(number == 240){cout<<"number is not 13!"<<endl;}
                if(number == 241){cout<<"number is not 13!"<<endl;}
                if(number == 242){cout<<"number is not 13!"<<endl;}
                if(number == 243){cout<<"number is not 13!"<<endl;}
                if(number == 244){cout<<"number is not 13!"<<endl;}
                if(number == 245){cout<<"number is not 13!"<<endl;}
                if(number == 246){cout<<"number is not 13!"<<endl;}
                if(number == 247){cout<<"number is not 13!"<<endl;}
                if(number == 248){cout<<"number is not 13!"<<endl;}
                if(number == 249){cout<<"number is not 13!"<<endl;}
                if(number == 250){cout<<"number is not 13!"<<endl;}
                if(number == 251){cout<<"number is not 13!"<<endl;}
                if(number == 252){cout<<"number is not 13!"<<endl;}
                if(number == 253){cout<<"number is not 13!"<<endl;}
                if(number == 254){cout<<"number is not 13!"<<endl;}
                if(number == 255){cout<<"number is not 13!"<<endl;}
                if(number == 256){cout<<"number is not 13!"<<endl;}
                if(number == 257){cout<<"number is not 13!"<<endl;}
                if(number == 258){cout<<"number is not 13!"<<endl;}
                if(number == 259){cout<<"number is not 13!"<<endl;}
                if(number == 260){cout<<"number is not 13!"<<endl;}
                if(number == 261){cout<<"number is not 13!"<<endl;}
                if(number == 262){cout<<"number is not 13!"<<endl;}
                if(number == 263){cout<<"number is not 13!"<<endl;}
                if(number == 264){cout<<"number is not 13!"<<endl;}
				if(number >= 265){cout<<"number is bigger than 265! maaan..."<<endl;}
				}
		}
